//Harken - Die of Death inspired Distortion
//A hunter that tracks prey by sound, featuring a noise meter system

// ===== MOVESPEED MODIFIERS =====

/datum/movespeed_modifier/harken_sprint
	variable = TRUE
	multiplicative_slowdown = -1.5  // Instant full sprint speed

/datum/movespeed_modifier/harken_immolate
	variable = TRUE
	multiplicative_slowdown = -1.0  // Speed boost while bleeding

/datum/movespeed_modifier/harken_enrage
	variable = TRUE
	multiplicative_slowdown = -1.0  // Speed boost while enraged

// ===== MAIN MOB DEFINITION =====

/mob/living/simple_animal/hostile/distortion/harken
	name = "Harken"
	desc = "A giant mechanical-looking yellow construct with long limbs."
	icon = 'ModularLobotomy/_Lobotomyicons/32x48.dmi'
	icon_state = "harken_calm"
	icon_living = "harken_calm"

	// Base stats
	maxHealth = 2000
	health = 2000

	// Damage resistances - weak to PALE
	damage_coeff = list(BRUTE = 1, RED_DAMAGE = 1, WHITE_DAMAGE = -1, BLACK_DAMAGE = 1, PALE_DAMAGE = 1.5)

	melee_damage_lower = 50
	melee_damage_upper = 50
	melee_damage_type = RED_DAMAGE
	rapid_melee = 1
	move_to_delay = 4
	ranged = TRUE
	stat_attack = HARD_CRIT
	attack_verb_continuous = "impales"
	attack_verb_simple = "impale"
	attack_sound = 'sound/distortions/the_adversary/minionattack.ogg'
	del_on_death = TRUE
	can_patrol = TRUE
	robust_searching = TRUE
	ranged_ignores_vision = TRUE

	fear_level = WAW_LEVEL

	// Action types
	attack_action_types = list(
		/datum/action/innate/distortion_attack/harken_agitation,
		/datum/action/innate/distortion_attack/harken_tangle,
		/datum/action/innate/distortion_attack/harken_immolate,
		/datum/action/innate/distortion_attack/toggle/harken_sprint,
		/datum/action/innate/distortion_attack/toggle/harken_theme,
	)

	// ===== NOISE SYSTEM VARIABLES =====
	/// Current noise level
	var/noise = 0
	/// Maximum noise (calculated based on civilians)
	var/max_noise = 50
	/// Is Harken currently enraged?
	var/enraged = FALSE
	/// Rate at which noise drains while enraged (per Life() tick)
	var/noise_drain_rate = 4
	/// Has the UI been revealed to humans? (triggers at 50%)
	var/ui_revealed = FALSE
	/// List of humans who can see the noise UI
	var/list/ui_viewers = list()
	/// Harken's own noise meter HUD
	var/atom/movable/screen/harken_noise/harken_hud
	/// Dictionary of human -> their noise meter HUD
	var/list/human_huds = list()

	// ===== SPRINT SYSTEM VARIABLES =====
	/// Current stamina
	var/stamina = 100.0
	/// Maximum stamina
	var/max_stamina = 100.0
	/// Is currently sprinting?
	var/sprinting = FALSE
	/// Minimum stamina to start sprinting (15%)
	var/min_sprint_stamina = 15.0
	/// Stamina drained per Life() tick while sprinting
	var/sprint_stamina_drain = 5.0
	/// Stamina regenerated per Life() tick when not sprinting
	var/stamina_regen_rate = 5.0
	/// Timer for stamina updates
	var/stamina_update_timer
	/// Stamina bar image
	var/image/stamina_bar

	// ===== MELEE VARIABLES =====
	/// Noise generated on melee hit
	var/melee_noise = 2
	/// Enraged melee damage
	var/melee_damage_enraged = 80

	// ===== AGITATION VARIABLES =====
	/// Agitation cooldown tracker
	var/agitation_cooldown = 0
	/// Agitation cooldown time
	var/agitation_cooldown_time = 20 SECONDS
	/// Agitation damage
	var/agitation_damage = 30
	/// Noise generated by agitation
	var/agitation_noise = 5
	/// Minimum line length for agitation
	var/agitation_line_length = 8
	/// Delay between each beam (1 tick = 0.1 seconds)
	var/agitation_beam_delay = 1

	// ===== TANGLE VARIABLES =====
	/// Tangle cooldown tracker
	var/tangle_cooldown = 0
	/// Tangle cooldown time
	var/tangle_cooldown_time = 25 SECONDS
	/// Noise on throwing javelin
	var/tangle_noise_throw = 1
	/// Noise on hitting target
	var/tangle_noise_hit = 5
	/// Noise on chain breaking
	var/tangle_noise_break = 10
	/// Harken heals 10% of their max HP
	var/tangle_heal_harken_percent = 0.10
	/// Target heals 50% of their max HP
	var/tangle_heal_target_percent = 0.50
	/// Damage multiplier while target is chained
	var/tangle_damage_mult = 1.25
	/// Speed of the throw_at pull
	var/tangle_throw_speed = 4
	/// Currently chained target
	var/mob/living/chained_target = null
	/// Maximum chain distance before breaking
	var/max_chain_distance = 10
	/// Chain beam visual
	var/datum/beam/chain_beam = null

	// ===== IMMOLATE VARIABLES =====
	/// Immolate cooldown tracker
	var/immolate_cooldown = 0
	/// Immolate cooldown time
	var/immolate_cooldown_time = 35 SECONDS
	/// Self-damage as percentage of max HP
	var/immolate_self_damage_percent = 0.20
	/// DoT damage as percentage of max HP
	var/immolate_dot_percent = 0.05
	/// Duration of DoT
	var/immolate_dot_duration = 10 SECONDS
	/// Noise as percentage of max noise meter
	var/immolate_noise_percent = 0.60
	/// Is currently bleeding from immolate?
	var/immolate_bleeding = FALSE

	// ===== STATE CONTROL =====
	/// Can perform actions?
	var/can_act = TRUE

	// ===== SCREEN TINT =====
	/// Red screen tint color for Harken player
	var/screen_tint_color = "#fde2e2ff"
	/// Original client color before tint was applied
	var/initial_client_color

	// ===== THEME MUSIC SYSTEM =====
	/// Path to calm theme
	var/calm_theme_path = 'sound/distortions/harken/harken_calm_theme.ogg'
	/// Calm theme length
	var/calm_theme_length = 45 SECONDS
	/// Path to enraged theme
	var/enraged_theme_path = 'sound/distortions/harken/harken_enraged_theme.ogg'
	/// Enraged theme length
	var/enraged_theme_length = 52 SECONDS
	/// Path to transition theme
	var/transition_theme_path = 'sound/distortions/harken/harken_transition_theme.ogg'
	/// Transition theme length
	var/transition_theme_length = 2 SECONDS
	/// Is theme currently active?
	var/theme_active = FALSE
	/// Theme volume
	var/theme_volume = 20
	/// Time when current theme track ends and needs to loop
	var/theme_stop = 0
	/// Currently playing enraged theme (vs calm theme)?
	var/playing_enraged_theme = FALSE
	/// Is the transition currently playing?
	var/transition_playing = FALSE

// ===== INITIALIZATION =====

/mob/living/simple_animal/hostile/distortion/harken/Initialize(mapload)
	// Prevent multiple Harkens from existing
	for(var/mob/living/simple_animal/hostile/distortion/harken/H in GLOB.alive_mob_list)
		if(H != src && H.stat != DEAD)
			return INITIALIZE_HINT_QDEL
	. = ..()
	// Apply noise trackers to all humans
	apply_noise_trackers()
	// Register for new mob creation
	RegisterSignal(SSdcs, COMSIG_GLOB_MOB_CREATED, PROC_REF(on_mob_created))
	// Start stamina update timer (0.5 second intervals)
	stamina_update_timer = addtimer(CALLBACK(src, PROC_REF(process_stamina)), 0.5 SECONDS, TIMER_STOPPABLE | TIMER_LOOP)
	// Calculate initial max_noise based on civilians
	update_max_noise()
	// Setup noise meter HUD
	setup_harken_hud()
	// Start playing calm theme
	start_theme()
	AddElement(/datum/element/waddling)

/mob/living/simple_animal/hostile/distortion/harken/Destroy()
	UnregisterSignal(SSdcs, COMSIG_GLOB_MOB_CREATED)
	remove_noise_trackers()
	remove_all_ui()
	deltimer(stamina_update_timer)
	remove_stamina_bar()
	stop_theme()
	// Restore original client color
	if(client)
		client.color = initial_client_color
	if(chain_beam)
		QDEL_NULL(chain_beam)
	chained_target = null
	return ..()

/mob/living/simple_animal/hostile/distortion/harken/Login()
	. = ..()
	if(!. || !client)
		return FALSE
	to_chat(src, "<h1>You are Harken, A Rhino Buster Distortion.</h1><br>\
		<b>|Echo Location|: Your noise meter fills when you or nearby humans make noise.<br>\
		When full, you enter an ENRAGED state with increased speed and projectile immunity.<br>\
		While enraged, your melee attacks pierce through mechs to damage pilots.<br>\
		<br>\
		|Sprint|: Toggle sprint for instant speed boost.<br>\
		Drains stamina while active. Requires at least 15% stamina to activate.<br>\
		<br>\
		|Agitation|: Click a turf to create a line of disruptive energy.<br>\
		Knocks targets into the air and deals 15 RED damage. 20 second cooldown.<br>\
		Ejects pilots from mechs below 50% integrity. After the line attack, releases an AOE knockup around you.<br>\
		<br>\
		|Tangle|: Throw a javelin to chain and yank a target toward you.<br>\
		Heals you for 10% of your max HP and heals the target for 50% of their max HP.<br>\
		Chained targets take 1.25x damage from your attacks. Pulls pilots out of mechs.<br>\
		25 second cooldown.<br>\
		<br>\
		|Immolate|: Impale yourself for power.<br>\
		Deals 20% of your max HP as immediate damage and 5% over 10 seconds.<br>\
		Generates 60% of your max noise meter. Grants speed boost while bleeding.<br>\
		Cannot be used while enraged. 35 second cooldown.</b>")
	update_stamina_bar()
	// Re-add HUD when player logs in
	if(harken_hud)
		client.screen += harken_hud
	update_all_noise_ui()
	// Save initial client color for enrage tint
	initial_client_color = client.color
	// Re-apply tint if already enraged
	if(enraged)
		client.color = screen_tint_color

/mob/living/simple_animal/hostile/distortion/harken/Logout()
	// Restore original client color before logout
	if(client && enraged)
		client.color = initial_client_color
	return ..()

// ===== LIFE PROCESSING =====

/mob/living/simple_animal/hostile/distortion/harken/Life()
	. = ..()
	if(!.)
		return FALSE
	process_noise_drain()
	process_chain()
	check_ui_reveal()
	process_theme()

// ===== NOISE SYSTEM =====

/// Add noise to the meter and check for enrage trigger
/mob/living/simple_animal/hostile/distortion/harken/proc/add_noise(amount)
	if(amount <= 0)
		return
	noise = min(noise + amount, max_noise)
	update_all_noise_ui()
	check_enrage()

/// Check if should enter or exit enrage state
/mob/living/simple_animal/hostile/distortion/harken/proc/check_enrage()
	if(!enraged && noise >= max_noise)
		enter_enrage()
	else if(enraged && noise <= 0)
		exit_enrage()

/// Enter enraged state
/mob/living/simple_animal/hostile/distortion/harken/proc/enter_enrage()
	if(enraged)
		return
	if(transition_playing)
		return

	// Start the transition - become immune to damage
	visible_message(span_danger("[src] begins to enter a frenzied state!"))
	icon_state = "harken_change"
	ChangeResistances(list(RED_DAMAGE = 0, WHITE_DAMAGE = 0, BLACK_DAMAGE = 0, PALE_DAMAGE = 0))

	// Transition to enraged theme (plays transition sound)
	swap_theme(TRUE)

	// Wait for transition to complete (2 seconds)
	addtimer(CALLBACK(src, PROC_REF(finish_enrage_transition)), transition_theme_length)

/// Complete the enrage transition after the delay
/mob/living/simple_animal/hostile/distortion/harken/proc/finish_enrage_transition()
	if(QDELETED(src) || stat == DEAD)
		return

	enraged = TRUE
	icon_state = "harken_enraged"

	// Restore resistances
	ChangeResistances(list(BRUTE = 1, RED_DAMAGE = 1, WHITE_DAMAGE = -1, BLACK_DAMAGE = 1, PALE_DAMAGE = 1.5))

	visible_message(span_danger("[src] becomes enraged, moving with terrifying speed!"))
	// Apply speed boost
	add_movespeed_modifier(/datum/movespeed_modifier/harken_enrage)
	// Reduce max stamina while enraged
	max_stamina = 75
	stamina = min(stamina, max_stamina)
	update_stamina_bar()
	// End immolate bleed if active (enrage overrides it)
	if(immolate_bleeding)
		end_immolate_bleed()
	// Apply red screen tint when enraged
	if(client)
		client.color = screen_tint_color
	update_all_noise_ui()

/// Exit enraged state
/mob/living/simple_animal/hostile/distortion/harken/proc/exit_enrage()
	if(!enraged)
		return
	enraged = FALSE
	icon_state = "harken_calm"
	visible_message(span_notice("[src] calms down, the frenzy subsiding."))
	// Remove speed boost
	remove_movespeed_modifier(/datum/movespeed_modifier/harken_enrage)
	// Restore max stamina
	max_stamina = 100
	update_stamina_bar()
	// Remove red screen tint
	if(client)
		client.color = initial_client_color
	update_all_noise_ui()
	// Transition to calm theme
	swap_theme(FALSE)

/// Process noise drain while enraged (called in Life())
/mob/living/simple_animal/hostile/distortion/harken/proc/process_noise_drain()
	if(!enraged)
		return
	noise = max(0, noise - noise_drain_rate)
	update_all_noise_ui()
	check_enrage()

/// Update max_noise based on living civilians on the same z-level
/mob/living/simple_animal/hostile/distortion/harken/proc/update_max_noise()
	var/civilian_count = 0
	for(var/mob/living/carbon/human/H in GLOB.alive_mob_list)
		if(H.z == z && H.stat != DEAD)
			civilian_count++
	max_noise = max(50, civilian_count * 5)  // Minimum 50, scales with civilians
	update_all_noise_ui()

// ===== THEME MUSIC SYSTEM =====

/// Start playing the theme music
/mob/living/simple_animal/hostile/distortion/harken/proc/start_theme()
	if(theme_active)
		return
	theme_active = TRUE
	playing_enraged_theme = FALSE
	theme_stop = world.time + calm_theme_length
	// Play initial calm theme
	play_theme_to_listeners(calm_theme_path)

/// Stop the theme music completely
/mob/living/simple_animal/hostile/distortion/harken/proc/stop_theme()
	if(!theme_active)
		return
	theme_active = FALSE
	// Stop music for Harken
	if(client)
		stop_sound_channel(CHANNEL_JUKEBOX)
	// Stop music for all listeners with the noise tracker
	for(var/mob/living/carbon/human/H in GLOB.alive_mob_list)
		var/datum/component/harken_noise_tracker/tracker = H.GetComponent(/datum/component/harken_noise_tracker)
		if(tracker && H.client)
			H.stop_sound_channel(CHANNEL_JUKEBOX)

/// Swap between calm and enraged themes with transition
/mob/living/simple_animal/hostile/distortion/harken/proc/swap_theme(to_enraged)
	if(!theme_active)
		return
	if(transition_playing)
		return
	// Only play transition when entering enraged state
	if(to_enraged)
		transition_playing = TRUE
		// Play transition sound to all listeners
		play_theme_to_listeners(transition_theme_path)
		// After transition ends, start the enraged theme
		addtimer(CALLBACK(src, PROC_REF(finish_theme_swap), to_enraged), transition_theme_length)
	else
		// Immediately switch to calm theme without transition
		finish_theme_swap(to_enraged)

/// Finish the theme swap after transition
/mob/living/simple_animal/hostile/distortion/harken/proc/finish_theme_swap(to_enraged)
	if(QDELETED(src))
		return
	transition_playing = FALSE
	playing_enraged_theme = to_enraged
	if(to_enraged)
		theme_stop = world.time + enraged_theme_length
		play_theme_to_listeners(enraged_theme_path)
	else
		theme_stop = world.time + calm_theme_length
		play_theme_to_listeners(calm_theme_path)

/// Process theme music each Life() tick
/mob/living/simple_animal/hostile/distortion/harken/proc/process_theme()
	if(!theme_active)
		return
	if(transition_playing)
		return
	// Check if the current track needs to loop
	if(world.time >= theme_stop)
		if(playing_enraged_theme)
			theme_stop = world.time + enraged_theme_length
			play_theme_to_listeners(enraged_theme_path)
		else
			theme_stop = world.time + calm_theme_length
			play_theme_to_listeners(calm_theme_path)

/// Play a theme to Harken and all humans (only after UI is revealed)
/mob/living/simple_animal/hostile/distortion/harken/proc/play_theme_to_listeners(theme_path)
	var/sound/song_played = sound(theme_path)
	// Play to Harken always
	if(client)
		playsound_local(get_turf(src), null, theme_volume, channel = CHANNEL_JUKEBOX, S = song_played, use_reverb = FALSE)
	// Only play to humans once UI has been revealed
	if(!ui_revealed)
		return
	// Play to all humans with noise tracker
	for(var/mob/living/carbon/human/H in GLOB.alive_mob_list)
		var/datum/component/harken_noise_tracker/tracker = H.GetComponent(/datum/component/harken_noise_tracker)
		if(!tracker)
			continue
		if(!H.client)
			continue
		if(!(H.client.prefs.toggles & SOUND_INSTRUMENTS))
			continue
		H.playsound_local(get_turf(H), null, theme_volume, channel = CHANNEL_JUKEBOX, S = song_played, use_reverb = FALSE)

// ===== ENRAGE COMBAT BONUSES =====

/// Projectile immunity while enraged
/mob/living/simple_animal/hostile/distortion/harken/bullet_act(obj/projectile/P)
	if(enraged)
		visible_message(span_warning("[P] dissipates harmlessly against [src]'s frenzied aura!"))
		playsound(src, 'sound/effects/attackblob.ogg', 50, TRUE)
		return BULLET_ACT_BLOCK
	return ..()

/// Deal damage to pilots inside mechs while enraged
/mob/living/simple_animal/hostile/distortion/harken/proc/deal_mech_piercing_damage(obj/vehicle/sealed/mecha/mech, damage)
	if(!enraged)
		return
	if(!istype(mech))
		return
	if(!LAZYLEN(mech.occupants))
		return
	// Deal 50% of attack damage to all occupants
	for(var/mob/living/occupant in mech.occupants)
		occupant.deal_damage(damage * 0.5, melee_damage_type, src)
		to_chat(occupant, span_userdanger("[src]'s attack pierces through [mech] and strikes you!"))
	visible_message(span_danger("[src]'s frenzied attack pierces through [mech]'s armor!"))

// ===== MELEE ATTACK =====

/mob/living/simple_animal/hostile/distortion/harken/AttackingTarget(atom/attacked_target)
	if(!can_act)
		return FALSE

	// Temporarily boost damage if enraged
	var/original_lower = melee_damage_lower
	var/original_upper = melee_damage_upper
	if(enraged)
		melee_damage_lower = melee_damage_enraged
		melee_damage_upper = melee_damage_enraged

	// Boost damage if target is chained
	if(chained_target && attacked_target == chained_target)
		melee_damage_lower = round(melee_damage_lower * tangle_damage_mult)
		melee_damage_upper = round(melee_damage_upper * tangle_damage_mult)

	// Generate noise from attacking living humans
	if(isliving(attacked_target))
		var/mob/living/L = attacked_target
		if(ishuman(L) && L.stat != DEAD)
			add_noise(melee_noise)

	// Mech-piercing damage when enraged
	if(istype(attacked_target, /obj/vehicle/sealed/mecha))
		var/obj/vehicle/sealed/mecha/mech = attacked_target
		var/damage = enraged ? melee_damage_enraged : rand(original_lower, original_upper)
		deal_mech_piercing_damage(mech, damage)
		// Gain noise from attacking mechs with pilots
		if(LAZYLEN(mech.occupants))
			add_noise(melee_noise)

	. = ..()

	// Restore original damage values
	melee_damage_lower = original_lower
	melee_damage_upper = original_upper

/mob/living/simple_animal/hostile/distortion/harken/Move()
	if(!can_act)
		return FALSE
	return ..()

// ===== SPRINT SYSTEM =====

/mob/living/simple_animal/hostile/distortion/harken/proc/start_sprint()
	if(sprinting)
		return
	if(stamina < min_sprint_stamina)
		to_chat(src, span_warning("Not enough stamina to sprint! Need at least [min_sprint_stamina]%."))
		return
	sprinting = TRUE
	add_movespeed_modifier(/datum/movespeed_modifier/harken_sprint)
	to_chat(src, span_nicegreen("You begin sprinting!"))

/mob/living/simple_animal/hostile/distortion/harken/proc/stop_sprint()
	if(!sprinting)
		return
	sprinting = FALSE
	remove_movespeed_modifier(/datum/movespeed_modifier/harken_sprint)
	to_chat(src, span_warning("You stop sprinting."))

/mob/living/simple_animal/hostile/distortion/harken/proc/process_stamina()
	if(QDELETED(src))
		return
	if(sprinting)
		stamina -= sprint_stamina_drain
		stamina = max(0, stamina)
		if(stamina <= 0)
			to_chat(src, span_warning("You've run out of stamina!"))
			stop_sprint()
	else
		stamina += stamina_regen_rate
		stamina = min(max_stamina, stamina)
	update_stamina_bar()

/mob/living/simple_animal/hostile/distortion/harken/proc/update_stamina_bar()
	if(!client)
		return
	if(stamina >= max_stamina)
		remove_stamina_bar()
		return
	if(!stamina_bar)
		create_stamina_bar()
	var/bar_percent = round(stamina, 5)
	stamina_bar.icon_state = "prog_bar_[bar_percent]"

/mob/living/simple_animal/hostile/distortion/harken/proc/create_stamina_bar()
	if(!client)
		return
	stamina_bar = image('icons/effects/progessbar.dmi', src, "prog_bar_100", HUD_LAYER)
	stamina_bar.plane = ABOVE_HUD_PLANE
	stamina_bar.appearance_flags = APPEARANCE_UI_IGNORE_ALPHA
	stamina_bar.pixel_y = 32
	client.images += stamina_bar

/mob/living/simple_animal/hostile/distortion/harken/proc/remove_stamina_bar()
	if(!stamina_bar)
		return
	if(client)
		client.images -= stamina_bar
	stamina_bar = null

// ===== PLAYER NOISE TRACKING COMPONENT =====

/datum/component/harken_noise_tracker
	dupe_mode = COMPONENT_DUPE_UNIQUE
	/// Reference to the Harken that added this component
	var/mob/living/simple_animal/hostile/distortion/harken/owner_harken
	/// Range within which noise is reported to Harken
	var/noise_range = 15
	/// Noise values for different actions
	var/throw_noise = 3
	var/melee_attack_noise = 4
	var/ranged_fire_noise = 2
	/// Noise value for mech attacks
	var/mech_attack_noise = 5
	/// Cooldown time between noise reports (2 seconds)
	var/noise_cooldown_time = 2 SECONDS
	/// Last time noise was reported
	var/last_noise_time = 0

/datum/component/harken_noise_tracker/Initialize(mob/living/simple_animal/hostile/distortion/harken/harken)
	. = ..()
	if(!ishuman(parent))
		return COMPONENT_INCOMPATIBLE
	owner_harken = harken

/datum/component/harken_noise_tracker/RegisterWithParent()
	RegisterSignal(parent, COMSIG_MOB_THROW, PROC_REF(on_throw))
	RegisterSignal(parent, COMSIG_MOB_ITEM_ATTACK, PROC_REF(on_melee_attack))
	RegisterSignal(parent, COMSIG_HUMAN_MELEE_UNARMED_ATTACK, PROC_REF(on_unarmed_attack))
	RegisterSignal(parent, COMSIG_MOB_FIRED_GUN, PROC_REF(on_ranged_fire))
	RegisterSignal(parent, COMSIG_MOB_CLICKON, PROC_REF(on_click))

/datum/component/harken_noise_tracker/UnregisterFromParent()
	UnregisterSignal(parent, list(
		COMSIG_MOB_THROW,
		COMSIG_MOB_ITEM_ATTACK,
		COMSIG_HUMAN_MELEE_UNARMED_ATTACK,
		COMSIG_MOB_FIRED_GUN,
		COMSIG_MOB_CLICKON
	))

/datum/component/harken_noise_tracker/proc/on_throw(datum/source, atom/target)
	SIGNAL_HANDLER
	report_noise(throw_noise)

/datum/component/harken_noise_tracker/proc/on_melee_attack(datum/source, mob/living/target, obj/item/weapon)
	SIGNAL_HANDLER
	report_noise(melee_attack_noise)

/datum/component/harken_noise_tracker/proc/on_unarmed_attack(datum/source, atom/target)
	SIGNAL_HANDLER
	report_noise(melee_attack_noise)

/datum/component/harken_noise_tracker/proc/on_ranged_fire(datum/source, obj/item/gun/gun, atom/target)
	SIGNAL_HANDLER
	report_noise(ranged_fire_noise)

/// Detect clicks when in a mech to track mech attacks
/datum/component/harken_noise_tracker/proc/on_click(datum/source, atom/target, params)
	SIGNAL_HANDLER
	var/mob/living/L = parent
	if(!istype(L))
		return

	// Check if the human is inside a mech
	var/obj/vehicle/sealed/mecha/mech = L.loc
	if(!istype(mech))
		return

	// Make sure the human is an occupant of the mech
	if(!(L in mech.occupants))
		return

	// Check if the mech can actually perform actions
	if(!mech.get_charge())
		return
	if(mech == target)
		return
	if(L.incapacitated())
		return
	if(mech.phasing)
		return
	if(mech.construction_state)
		return

	// Check for mech equipment ranged attack
	if(mech.selected)
		var/obj/item/mecha_parts/mecha_equipment/selected = mech.selected
		// Ranged attack: equipment has ranged capability and target is not adjacent
		if(!mech.Adjacent(target) && (selected.range & MECHA_RANGED))
			report_noise(mech_attack_noise)
			return
		// Melee equipment attack: equipment has melee capability and target is adjacent
		if((selected.range & MECHA_MELEE) && mech.Adjacent(target))
			report_noise(mech_attack_noise)
			return

	// Check for mech fist melee attack (no equipment selected, adjacent target)
	if(mech.Adjacent(target) && istype(target, /atom))
		report_noise(mech_attack_noise)

/datum/component/harken_noise_tracker/proc/report_noise(amount)
	// Check cooldown
	if(world.time < last_noise_time + noise_cooldown_time)
		return
	last_noise_time = world.time

	var/mob/living/L = parent
	if(!istype(L))
		return
	// Find all Harken mobs in range and report noise to them
	for(var/mob/living/simple_animal/hostile/distortion/harken/H in range(noise_range, L))
		if(H.stat == DEAD)
			continue
		if(H.z != L.z)
			continue
		H.add_noise(amount)

// ===== HARKEN NOISE TRACKER MANAGEMENT =====

/mob/living/simple_animal/hostile/distortion/harken/proc/apply_noise_trackers()
	for(var/mob/living/carbon/human/H in GLOB.alive_mob_list)
		if(H.z != z)
			continue
		if(H.stat == DEAD)
			continue
		H.AddComponent(/datum/component/harken_noise_tracker, src)

/mob/living/simple_animal/hostile/distortion/harken/proc/on_mob_created(datum/source, mob/created_mob)
	SIGNAL_HANDLER
	if(!ishuman(created_mob))
		return
	var/mob/living/carbon/human/H = created_mob
	INVOKE_ASYNC(src, PROC_REF(try_add_tracker_to_new_mob), H)
	update_max_noise()

/mob/living/simple_animal/hostile/distortion/harken/proc/try_add_tracker_to_new_mob(mob/living/carbon/human/H)
	sleep(5)
	if(QDELETED(H) || QDELETED(src))
		return
	if(H.z != z)
		return
	if(H.stat == DEAD)
		return
	var/datum/component/harken_noise_tracker/existing = H.GetComponent(/datum/component/harken_noise_tracker)
	if(existing && existing.owner_harken == src)
		return
	H.AddComponent(/datum/component/harken_noise_tracker, src)

/mob/living/simple_animal/hostile/distortion/harken/proc/remove_noise_trackers()
	for(var/mob/living/carbon/human/H in GLOB.alive_mob_list)
		var/datum/component/harken_noise_tracker/tracker = H.GetComponent(/datum/component/harken_noise_tracker)
		if(tracker && tracker.owner_harken == src)
			qdel(tracker)

// ===== UI SYSTEM =====

// Screen object for the noise meter HUD
/atom/movable/screen/harken_noise
	name = "Noise Meter"
	icon = 'icons/hud/screen_harken.dmi'
	icon_state = "noisebar_calm_0"
	screen_loc = "CENTER,NORTH-1"
	pixel_x = -169  // Center the 199px wide icon (-99) plus 70px left shift
	mouse_opacity = MOUSE_OPACITY_TRANSPARENT
	layer = ABOVE_HUD_LAYER

	/// Weak reference to the harken this HUD belongs to
	var/datum/weakref/harken_ref
	/// Current displayed percentage
	var/current_percent = 0
	/// Current enraged state
	var/current_enraged = FALSE

/// Update the noise meter display
/atom/movable/screen/harken_noise/proc/update_display(noise, max_noise, enraged)
	// Calculate percentage rounded to nearest 5
	var/raw_percent = (noise / max_noise) * 100
	var/new_percent = clamp(round(raw_percent, 5), 0, 100)

	// Determine state prefix
	var/state_prefix = enraged ? "enraged" : "calm"

	// Only update if changed
	if(new_percent != current_percent || enraged != current_enraged)
		current_percent = new_percent
		current_enraged = enraged
		icon_state = "noisebar_[state_prefix]_[new_percent]"

/// Setup Harken's own noise meter HUD
/mob/living/simple_animal/hostile/distortion/harken/proc/setup_harken_hud()
	harken_hud = new()
	harken_hud.harken_ref = WEAKREF(src)
	if(client)
		client.screen += harken_hud
	update_all_noise_ui()

/mob/living/simple_animal/hostile/distortion/harken/proc/check_ui_reveal()
	if(ui_revealed)
		return
	var/noise_percent = (noise / max_noise) * 100
	if(noise_percent >= 50)
		ui_revealed = TRUE
		reveal_ui_to_humans()

/mob/living/simple_animal/hostile/distortion/harken/proc/reveal_ui_to_humans()
	for(var/mob/living/carbon/human/H in GLOB.alive_mob_list)
		if(H.z != z)
			continue
		add_ui_to_human(H)
	// Play alert sound
	for(var/mob/living/carbon/human/H in ui_viewers)
		to_chat(H, span_userdanger("You sense a rising tension in the air..."))

/mob/living/simple_animal/hostile/distortion/harken/proc/add_ui_to_human(mob/living/carbon/human/H)
	if(!H?.client)
		return
	if(H in ui_viewers)
		return
	ui_viewers += H
	// Create a noise meter HUD for this human
	var/atom/movable/screen/harken_noise/human_hud = new()
	human_hud.harken_ref = WEAKREF(src)
	human_huds[H] = human_hud
	H.client.screen += human_hud
	update_human_hud(H)

/mob/living/simple_animal/hostile/distortion/harken/proc/remove_all_ui()
	// Remove Harken's own HUD
	if(harken_hud && client)
		client.screen -= harken_hud
	QDEL_NULL(harken_hud)
	// Remove HUDs from all human viewers
	for(var/mob/living/carbon/human/H in ui_viewers)
		var/atom/movable/screen/harken_noise/hud = human_huds[H]
		if(hud && H.client)
			H.client.screen -= hud
		qdel(hud)
	human_huds = list()
	ui_viewers = list()

/mob/living/simple_animal/hostile/distortion/harken/proc/update_all_noise_ui()
	// Update Harken's own HUD
	if(harken_hud)
		harken_hud.update_display(noise, max_noise, enraged)
	// Update all human viewers
	for(var/mob/living/carbon/human/H in ui_viewers)
		update_human_hud(H)

/// Update a specific human's noise meter HUD
/mob/living/simple_animal/hostile/distortion/harken/proc/update_human_hud(mob/living/carbon/human/H)
	var/atom/movable/screen/harken_noise/hud = human_huds[H]
	if(hud)
		hud.update_display(noise, max_noise, enraged)

// ===== AGITATION ABILITY =====

/// Yellow version of the beam effect
/obj/effect/temp_visual/harken_agitation_beam
	name = "agitation wave"
	desc = "A wave of disruptive energy."
	icon = 'icons/effects/96x96.dmi'
	icon_state = "beamout"
	pixel_x = -32
	base_pixel_x = -32
	color = "#FFCC00"  // Yellow tint
	randomdir = FALSE
	duration = 4.2
	layer = POINT_LAYER

/// Yellow warning tile for Harken abilities
/obj/effect/temp_visual/harken_warning
	name = "ominous glow"
	icon = 'icons/effects/effects.dmi'
	icon_state = "spreadwarning"
	layer = BELOW_MOB_LAYER
	duration = 10  // 1 second
	alpha = 128
	color = "#FFCC00"  // Yellow tint to match Harken's theme

/mob/living/simple_animal/hostile/distortion/harken/proc/fire_agitation(atom/target)
	if(agitation_cooldown > world.time)
		to_chat(src, span_warning("Agitation is on cooldown! ([round((agitation_cooldown - world.time) / 10, 0.1)]s remaining)"))
		return
	if(!isturf(target))
		target = get_turf(target)
	if(!target)
		return

	can_act = FALSE
	agitation_cooldown = world.time + agitation_cooldown_time

	// Generate noise on use
	add_noise(agitation_noise)

	// Add yellow blip overlay during windup
	var/mutable_appearance/blip_overlay = mutable_appearance('icons/effects/effects.dmi', "blip")
	blip_overlay.color = "#FFCC00"  // Yellow tint
	add_overlay(blip_overlay)

	// Windup sound and message
	playsound(src, 'sound/distortions/harken/harken_agitation.ogg', 50, TRUE, 7)
	visible_message(span_danger("[src] prepares a wave of agitation!"))

	// 1 second windup delay
	sleep(10)

	if(QDELETED(src) || stat == DEAD)
		can_act = TRUE
		return

	// === LINE ATTACK (FIRST) ===
	// Get the line of turfs from Harken to target
	var/list/turf/line_turfs = getline(src, target)

	// Extend line to minimum length if needed
	if(line_turfs.len < agitation_line_length)
		var/dir_to_target = get_dir(src, target)
		var/turf/last_turf = line_turfs[line_turfs.len]
		while(line_turfs.len < agitation_line_length)
			var/turf/next_turf = get_step(last_turf, dir_to_target)
			if(!next_turf)
				break
			line_turfs += next_turf
			last_turf = next_turf

	visible_message(span_danger("[src] releases a wave of agitation!"))

	// Create beams along the line with delay
	for(var/turf/T in line_turfs)
		// Skip our own tile
		if(T == get_turf(src))
			continue

		// Create the yellow beam effect
		new /obj/effect/temp_visual/harken_agitation_beam(T)
		playsound(T, 'sound/effects/bang.ogg', 30, TRUE)

		// Check for mobs on this tile and knock them up (with damage)
		for(var/mob/living/L in T)
			if(L == src)
				continue
			agitation_knockup(L, TRUE)  // With damage

		// Check for mechs on this tile and eject pilots (only if mech is below 50% HP)
		for(var/obj/vehicle/sealed/mecha/mech in T)
			if(mech.obj_integrity <= mech.max_integrity * 0.5)
				var/mob/living/pilot = extract_pilot_from_mech(mech)
				if(pilot)
					agitation_knockup(pilot, TRUE)  // With damage

		// Delay before next beam
		sleep(agitation_beam_delay)

	// === SCREECH AOE EFFECT (1 SECOND AFTER LINE ATTACK) ===
	sleep(10)  // 1 second delay

	// Remove overlay after windup
	cut_overlay(blip_overlay)


	if(QDELETED(src) || stat == DEAD)
		can_act = TRUE
		return

	// Sound effect
	playsound(src, 'sound/effects/screech.ogg', 60, TRUE)

	// Create yellow screech temp_visual
	var/obj/effect/temp_visual/screech/screech_effect = new(get_turf(src))
	screech_effect.color = "#FFCC00"  // Yellow tint

	// Knock up all humans within 2 view range (no damage)
	for(var/mob/living/carbon/human/H in oview(2, src))
		agitation_knockup(H, FALSE)  // No damage

	can_act = TRUE
	chosen_attack = 0

/// Knock a mob into the air with animation and spin
/mob/living/simple_animal/hostile/distortion/harken/proc/agitation_knockup(mob/living/victim, deal_damage = TRUE)
	if(QDELETED(victim))
		return

	// Deal damage only if specified
	if(deal_damage)
		victim.deal_damage(agitation_damage, RED_DAMAGE, src)

	// Start the knockup animation
	var/original_pixel_y = victim.pixel_y
	var/knockup_height = 32

	// Animate upward
	animate(victim, pixel_y = original_pixel_y + knockup_height, time = 3, easing = SINE_EASING)

	// Start spinning while in air
	victim.SpinAnimation(speed = 10, loops = 2, clockwise = 1, segments = 3, parallel = TRUE)

	// Animate back down after a delay
	addtimer(CALLBACK(src, PROC_REF(agitation_knockdown), victim, original_pixel_y), 5)

/// Bring the mob back down after knockup
/mob/living/simple_animal/hostile/distortion/harken/proc/agitation_knockdown(mob/living/victim, original_pixel_y)
	if(QDELETED(victim))
		return

	// Animate downward
	animate(victim, pixel_y = original_pixel_y, time = 3, easing = BOUNCE_EASING)

	// Apply brief knockdown on landing
	victim.Knockdown(10)  // 1 second knockdown

// ===== TANGLE ABILITY =====

/// Tangle javelin projectile
/obj/projectile/harken_tangle
	name = "light javelin"
	icon = 'icons/obj/projectiles.dmi'
	icon_state = "gaussstrong"
	damage = 0
	speed = 1.5
	hitsound = 'sound/weapons/chainhit.ogg'
	var/mob/living/simple_animal/hostile/distortion/harken/owner_harken

/obj/projectile/harken_tangle/on_hit(atom/target, blocked = FALSE)
	. = ..()
	if(owner_harken && !QDELETED(owner_harken))
		owner_harken.on_tangle_hit(target)
	return BULLET_ACT_HIT

/mob/living/simple_animal/hostile/distortion/harken/proc/fire_tangle(atom/target)
	if(tangle_cooldown > world.time)
		to_chat(src, span_warning("Tangle is on cooldown! ([round((tangle_cooldown - world.time) / 10, 0.1)]s remaining)"))
		return
	if(chained_target)
		to_chat(src, span_warning("You already have a target chained!"))
		return

	can_act = FALSE
	tangle_cooldown = world.time + tangle_cooldown_time

	// Generate noise on throw
	add_noise(tangle_noise_throw)

	face_atom(target)
	playsound(src, 'sound/distortions/harken/harken_tangle_throw.ogg', 50, TRUE)
	visible_message(span_danger("[src] prepares to hurl a light javelin!"))

	// Get line of turfs for warning tiles, stopping at walls
	var/turf/start_turf = get_turf(src)
	var/turf/target_turf = get_turf(target)
	var/list/turf/warning_turfs = list()

	if(start_turf && target_turf)
		var/list/turf/line_turfs = getline(start_turf, target_turf)
		for(var/turf/T in line_turfs)
			// Skip our own tile
			if(T == start_turf)
				continue
			// Stop at walls
			if(T.density)
				break
			warning_turfs += T
			// Create warning tile
			new /obj/effect/temp_visual/harken_warning(T)

	// 1 second windup delay
	sleep(10)

	if(QDELETED(src) || stat == DEAD)
		can_act = TRUE
		return

	visible_message(span_danger("[src] hurls a light javelin!"))

	// Fire projectile
	var/obj/projectile/harken_tangle/P = new(get_turf(src))
	P.owner_harken = src
	P.preparePixelProjectile(target, get_turf(src))
	P.fire()

	can_act = TRUE
	chosen_attack = 0

/// Called when tangle javelin hits a target
/mob/living/simple_animal/hostile/distortion/harken/proc/on_tangle_hit(atom/target)
	if(QDELETED(target))
		return
	if(chained_target)
		return

	var/mob/living/victim = null

	// Check if we hit a mech - extract pilot first
	if(istype(target, /obj/vehicle/sealed/mecha))
		var/obj/vehicle/sealed/mecha/mech = target
		victim = extract_pilot_from_mech(mech)
		if(!victim)
			return
	else if(isliving(target))
		var/mob/living/L = target
		if(L.stat == DEAD)
			return
		victim = L
	else
		return

	// Chain and yank the victim
	begin_chain_pull(victim)

/// Forcibly extracts pilot from mech and returns them
/mob/living/simple_animal/hostile/distortion/harken/proc/extract_pilot_from_mech(obj/vehicle/sealed/mecha/mech)
	if(!mech || !LAZYLEN(mech.occupants))
		return null

	var/mob/living/pilot = null
	for(var/mob/living/occupant in mech.occupants)
		if(ishuman(occupant))
			pilot = occupant
			break
		if(!pilot)
			pilot = occupant

	if(!pilot)
		return null

	visible_message(span_danger("[src] rips [pilot] out of [mech]!"))
	playsound(mech, 'sound/effects/meteorimpact.ogg', 50, TRUE)
	mech.mob_exit(pilot, FALSE, TRUE)

	return pilot

/// Chains target and performs one strong pull using throw_at()
/mob/living/simple_animal/hostile/distortion/harken/proc/begin_chain_pull(mob/living/victim)
	chained_target = victim

	// Generate noise on hit
	add_noise(tangle_noise_hit)

	// Both gain HP (percentage-based)
	var/harken_heal = maxHealth * tangle_heal_harken_percent
	var/target_heal = victim.maxHealth * tangle_heal_target_percent
	adjustBruteLoss(-harken_heal)
	victim.adjustBruteLoss(-target_heal)

	// Apply chained status effect
	victim.apply_status_effect(/datum/status_effect/harken_chained, src)

	// Create visual chain beam
	chain_beam = Beam(victim, icon_state = "chain", time = INFINITY, maxdistance = max_chain_distance + 5)

	visible_message(span_danger("[src] chains [victim] and yanks them close!"))
	playsound(src, 'sound/distortions/harken/harken_tangle_hit.ogg', 25, TRUE)

	// Calculate distance for the throw
	var/pull_distance = get_dist(src, victim)
	var/turf/my_turf = get_turf(src)

	// One strong pull - throw them directly at Harken
	victim.throw_at(
		target = my_turf,
		range = pull_distance,
		speed = tangle_throw_speed,
		thrower = src,
		spin = FALSE,
		gentle = TRUE
	)

/// Process chain state each Life() tick
/mob/living/simple_animal/hostile/distortion/harken/proc/process_chain()
	if(!chained_target)
		return

	// Check if target is too far
	if(get_dist(src, chained_target) > max_chain_distance)
		break_chain()
		return

	// Check if target is dead
	if(chained_target.stat == DEAD)
		break_chain()
		return

	// Check if we're stunned
	if(IsStun() || IsParalyzed() || HAS_TRAIT(src, TRAIT_KNOCKEDOUT))
		break_chain()
		return

/// Break the chain connection
/mob/living/simple_animal/hostile/distortion/harken/proc/break_chain()
	if(!chained_target)
		return

	visible_message(span_notice("The chain connecting [src] to [chained_target] shatters!"))
	playsound(src, 'sound/distortions/harken/harken_tangle_break.ogg', 25, TRUE)

	// Generate noise on break
	add_noise(tangle_noise_break)

	// Remove status effect from target
	chained_target.remove_status_effect(/datum/status_effect/harken_chained)

	// Clean up beam
	if(chain_beam)
		QDEL_NULL(chain_beam)
	chained_target = null

// ===== HARKEN CHAINED STATUS EFFECT =====

/datum/status_effect/harken_chained
	id = "harken_chained"
	status_type = STATUS_EFFECT_UNIQUE
	alert_type = /atom/movable/screen/alert/status_effect/harken_chained
	/// Reference to the Harken that chained us
	var/mob/living/simple_animal/hostile/distortion/harken/harken_owner

/datum/status_effect/harken_chained/on_creation(mob/living/new_owner, mob/living/simple_animal/hostile/distortion/harken/harken_ref)
	harken_owner = harken_ref
	return ..()

/datum/status_effect/harken_chained/on_apply()
	to_chat(owner, span_userdanger("You've been chained by [harken_owner]!"))
	return TRUE

/datum/status_effect/harken_chained/on_remove()
	to_chat(owner, span_notice("The chain releases you!"))

/atom/movable/screen/alert/status_effect/harken_chained
	name = "Chained"
	desc = "You've been caught by Harken's chain! You take increased damage from it."
	icon_state = "intenselight"

// ===== IMMOLATE ABILITY =====

/mob/living/simple_animal/hostile/distortion/harken/proc/activate_immolate()
	if(immolate_cooldown > world.time)
		to_chat(src, span_warning("Immolate is on cooldown! ([round((immolate_cooldown - world.time) / 10, 0.1)]s remaining)"))
		return
	if(enraged)
		to_chat(src, span_warning("You cannot use Immolate while enraged!"))
		return
	if(immolate_bleeding)
		to_chat(src, span_warning("You are already bleeding!"))
		return

	can_act = FALSE
	immolate_cooldown = world.time + immolate_cooldown_time

	// Sound and visual
	playsound(src, 'sound/distortions/harken/harken_immolate.ogg', 50, TRUE)
	visible_message(span_danger("[src] impales itself with a light javelin!"))

	// Calculate damage based on max HP
	var/immediate_damage = maxHealth * immolate_self_damage_percent
	var/total_dot_damage = maxHealth * immolate_dot_percent

	// Deal immediate self-damage
	adjustBruteLoss(immediate_damage)

	// Generate noise (60% of max noise meter)
	var/noise_amount = max_noise * immolate_noise_percent
	add_noise(noise_amount)

	// Start bleeding and speed boost
	immolate_bleeding = TRUE
	add_movespeed_modifier(/datum/movespeed_modifier/harken_immolate)

	// Start the DoT proc
	start_immolate_dot(total_dot_damage, immolate_dot_duration)

	can_act = TRUE
	chosen_attack = 0

/// Proc-based damage over time for Immolate
/mob/living/simple_animal/hostile/distortion/harken/proc/start_immolate_dot(total_damage, duration)
	set waitfor = FALSE

	var/tick_interval = 1 SECONDS
	var/num_ticks = duration / tick_interval
	var/damage_per_tick = total_damage / num_ticks

	for(var/i in 1 to num_ticks)
		if(QDELETED(src))
			return
		if(stat == DEAD)
			end_immolate_bleed()
			return
		if(!immolate_bleeding)  // Ended early (e.g., by enrage)
			return

		// Deal DoT damage
		adjustBruteLoss(damage_per_tick)

		// Visual bleed effect
		new /obj/effect/temp_visual/dir_setting/bloodsplatter(get_turf(src), pick(GLOB.alldirs))

		sleep(tick_interval)

	end_immolate_bleed()

/// End the immolate bleed effect
/mob/living/simple_animal/hostile/distortion/harken/proc/end_immolate_bleed()
	if(!immolate_bleeding)
		return
	immolate_bleeding = FALSE
	remove_movespeed_modifier(/datum/movespeed_modifier/harken_immolate)
	visible_message(span_notice("[src]'s bleeding stops."))

// ===== OPENFIRE HANDLER =====

/mob/living/simple_animal/hostile/distortion/harken/OpenFire(atom/A)
	if(!can_act)
		return

	switch(chosen_attack)
		if(1)  // Agitation
			fire_agitation(A)
			return
		if(2)  // Tangle
			fire_tangle(A)
			return
		if(3)  // Immolate
			activate_immolate()
			return

	return ..()

// ===== ACTION DATUMS =====

// Action 1: Agitation
/datum/action/innate/distortion_attack/harken_agitation
	name = "Agitation"
	icon_icon = 'icons/hud/screen_harken_skills.dmi'
	button_icon_state = "agitation"
	chosen_attack_num = 1
	chosen_message = span_notice("Agitation selected. Click a turf to create a disruptive wave.")

/datum/action/innate/distortion_attack/harken_agitation/Activate()
	var/mob/living/simple_animal/hostile/distortion/harken/H = owner
	if(!istype(H))
		return
	if(H.agitation_cooldown > world.time)
		to_chat(H, span_warning("Agitation is on cooldown! ([round((H.agitation_cooldown - world.time) / 10, 0.1)]s remaining)"))
		return
	to_chat(H, chosen_message)
	H.chosen_attack = chosen_attack_num

// Action 2: Tangle
/datum/action/innate/distortion_attack/harken_tangle
	name = "Tangle"
	icon_icon = 'icons/hud/screen_harken_skills.dmi'
	button_icon_state = "tangle"
	chosen_attack_num = 2
	chosen_message = span_notice("Tangle selected. Click a target to throw a chaining javelin.")

/datum/action/innate/distortion_attack/harken_tangle/Activate()
	var/mob/living/simple_animal/hostile/distortion/harken/H = owner
	if(!istype(H))
		return
	if(H.tangle_cooldown > world.time)
		to_chat(H, span_warning("Tangle is on cooldown! ([round((H.tangle_cooldown - world.time) / 10, 0.1)]s remaining)"))
		return
	if(H.chained_target)
		to_chat(H, span_warning("You already have a target chained!"))
		return
	to_chat(H, chosen_message)
	H.chosen_attack = chosen_attack_num

// Action 3: Immolate
/datum/action/innate/distortion_attack/harken_immolate
	name = "Immolate"
	icon_icon = 'icons/hud/screen_harken_skills.dmi'
	button_icon_state = "immolate"
	chosen_attack_num = 3
	chosen_message = span_notice("Immolate selected. Click to impale yourself for power.")

/datum/action/innate/distortion_attack/harken_immolate/Activate()
	var/mob/living/simple_animal/hostile/distortion/harken/H = owner
	if(!istype(H))
		return
	if(H.immolate_cooldown > world.time)
		to_chat(H, span_warning("Immolate is on cooldown! ([round((H.immolate_cooldown - world.time) / 10, 0.1)]s remaining)"))
		return
	if(H.enraged)
		to_chat(H, span_warning("You cannot use Immolate while enraged!"))
		return
	if(H.immolate_bleeding)
		to_chat(H, span_warning("You are already bleeding!"))
		return
	to_chat(H, chosen_message)
	H.chosen_attack = chosen_attack_num

// Action 4: Sprint Toggle
/datum/action/innate/distortion_attack/toggle/harken_sprint
	name = "Sprint"
	icon_icon = 'icons/hud/screen_harken_skills.dmi'
	button_icon_state = "sprint_off"
	chosen_attack_num = 0
	button_icon_toggle_activated = "sprint_on"
	button_icon_toggle_deactivated = "sprint_off"

/datum/action/innate/distortion_attack/toggle/harken_sprint/Activate()
	var/mob/living/simple_animal/hostile/distortion/harken/H = A
	if(!istype(H))
		return
	if(!H.sprinting)
		H.start_sprint()
		if(H.sprinting)
			button_icon_state = button_icon_toggle_activated
			UpdateButtonIcon()
			active = TRUE
	else
		to_chat(H, span_warning("Already sprinting!"))

/datum/action/innate/distortion_attack/toggle/harken_sprint/Deactivate()
	var/mob/living/simple_animal/hostile/distortion/harken/H = A
	if(!istype(H))
		return
	H.stop_sprint()
	button_icon_state = button_icon_toggle_deactivated
	UpdateButtonIcon()
	active = FALSE

// Action 5: Theme Toggle
/datum/action/innate/distortion_attack/toggle/harken_theme
	name = "Theme Music"
	icon_icon = 'icons/hud/screen_harken_skills.dmi'
	button_icon_state = "music_on"
	chosen_attack_num = 0
	button_icon_toggle_activated = "music_on"
	button_icon_toggle_deactivated = "music_off"

/datum/action/innate/distortion_attack/toggle/harken_theme/New()
	. = ..()
	// Theme starts active by default
	active = TRUE

/datum/action/innate/distortion_attack/toggle/harken_theme/Activate()
	var/mob/living/simple_animal/hostile/distortion/harken/H = owner
	if(!istype(H))
		return
	if(!H.theme_active)
		H.start_theme()
		button_icon_state = button_icon_toggle_activated
		UpdateButtonIcon()
		active = TRUE
	else
		to_chat(H, span_warning("Theme is already playing!"))

/datum/action/innate/distortion_attack/toggle/harken_theme/Deactivate()
	var/mob/living/simple_animal/hostile/distortion/harken/H = owner
	if(!istype(H))
		return
	H.stop_theme()
	button_icon_state = button_icon_toggle_deactivated
	UpdateButtonIcon()
	active = FALSE
